---

- hosts: all
  gather_facts: yes
  become: yes
  roles: 
    - { role: k8s_builder }
    - { role: nfs_storage, become: no, when: (node_type == 'control-plane') and (nfs_servers is defined) }
    - { role: metallb, become: no, when: node_type == 'control-plane' }
