---
# tasks file for k8s_builder for all nodes

- name: remove swap line in fstab
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  register: fstab_result
  loop:
    - swap
    - none

- name: swap off
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: reboot the system
  ansible.builtin.reboot:
    msg: rebooting to apply swap changes
  when: fstab_result is changed

- name: load containerd prereq
  ansible.builtin.command: "{{ item }}"
  loop:
    - modprobe overlay
    - modprobe br_netfilter

- name: add containerd config
  ansible.builtin.lineinfile:
    path: "/etc/modules-load.d/containerd.conf"
    line: "{{ item }}"
    create: yes
    mode: "0644"
  loop:
    - overlay
    - br_netfilter

- name: apply sysctl params
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    sysctl_file: "/etc/sysctl.d/99-kubernetes-cri.conf"
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-ip6tables

- name: make sure containerd config directory exist
  ansible.builtin.file:
    path: "/etc/containerd"
    state: directory
    mode: "0644"
  register: containerd_dir_created

- name: add apt signing keys for kubernetes
  ansible.builtin.apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present

- name: add kubernetes repo
  ansible.builtin.apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: kubernetes.list
  register: repo_added

- name: install packages
  ansible.builtin.apt:
    name: "{{ item }}={{ kube_version }}"
    state: present
    force_apt_get: yes
  register: installed_packages
  loop: "{{ kube_packages }}"

- name: install containerd
  ansible.builtin.apt:
    name: 
      - containerd
      - python3-pip
    state: present
    force_apt_get: yes
    update_cache: yes
  register: containerd_installed

- name: hold packages from being upgraded
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  when: installed_packages is changed and containerd_installed is changed
  loop: "{{ kube_packages + ['containerd'] }}"

- name: generate containerd config
  ansible.builtin.command: containerd config default
  register: containerd_config
  when: containerd_dir_created is changed

- name: save output to a file
  ansible.builtin.lineinfile:
    line: "{{ containerd_config.stdout }}"
    path: "{{ containerd_file }}"
    create: yes
    mode: "0644"
  register: containerd_config_exist
  when: containerd_config is changed

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: configure node ip
  ansible.builtin.lineinfile:
    path: "{{ kubelet_default }}"
    line: "KUBELET_EXTRA_ARGS=--node-ip={{ ansible_eth1['ipv4']['address'] }}"
    create: yes
    mode: "0644"
  notify: "restart kubelet service"

- name: set node type
  ansible.builtin.set_fact:
    node_type: "{{ 'control-plane' if ('cp1' in inventory_hostname) else 
                   'backup-plane' if ('cpb' in inventory_hostname) else 
                   'worker' if ('node' in inventory_hostname) }}"

- name: "working on {{ node_type }}"
  ansible.builtin.include_tasks: "{{ node_type }}.yml"

- block:
    - name: update node role
      kubernetes.core.k8s:
        state: patched
        kind: Node
        name: 
        definition:
          metadata:
            name: "{{ ansible_hostname }}"
            labels:
              kubernetes.io/role: "{{ node_type  }}"
  become_user: "{{ user }}"
  delegate_to: "{{ groups['cp1'][0] }}"

- name: installing helm
  ansible.builtin.include_tasks: helm.yml
  when: node_type == 'control-plane'
