---
# handlers file for k8s_builder

- name: restart kubelet service
  service:
    name: kubelet
    state: restarted
    enabled: yes

- name: restart containerd service
  service:
    name: containerd
    state: restarted
    enabled: yes

- name: add helm bash completion
  shell: helm completion bash > /etc/bash_completion.d/helm

- name: deploy CNI plugin
  ansible.builtin.k8s:
    state: present
    src: "{{ calico_file.dest }}"
  become_user: "(( user ))"
    
    