# This is a basic workflow to help you get started with Actions

name: Lint ansible playbook

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          sudo apt update
          sudo apt install virtualbox
          curl -O https://releases.hashicorp.com/vagrant/2.2.15/vagrant_2.2.15_x86_64.deb
          sudo apt install ./vagrant_2.2.15_x86_64.deb

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: vagrant validate
#           pip3 list | grep virtualenv || pip3 install virtualenv
#           mkdir vagrant_venv && python3 -m venv $(pwd)/vagrant_venv
#           source vagrant_venv/bin/activate
#           pip3 install -r requirements.txt
          
      - name: Lint Ansible Playbook
        # replace "master" with any valid ref
        uses: ansible/ansible-lint-action@master
        with:
          # [required]
          targets: cluster_setup.yml
          # [optional]
          # Arguments to override a package and its version to be set explicitly.
          # Must follow the example syntax.
          override-deps: |
            ansible==2.10
            ansible-lint==4.2.0

